config/routes.rb
Rails.application.routes.draw do
   get 'book/list'
   devise_for :users, controllers: { sessions: "session/new" }
   get 'book/new'
   root 'session#new'
   post 'book/create'
   post 'employees/create'
   get 'employees/list'
   get 'employees/show'
   get 'employees/new'
   get 'employees/edit'
   get 'employees/update'
   post 'manager/create'
   get 'manager/list'
   get 'manager/show'
   get 'manager/new'
   patch 'book/update'
   get 'book/list'
   get 'book/show'
   get 'book/edit'
   get 'book/delete'
   get 'book/update'
   get 'book/show_subjects'
   get 'user/list'
   get 'user/new'
   post 'user/create'
   get 'user/show'
   get 'application/session_time'
   match 'active'  => 'session#active',  via: :get
   match 'timeout' => 'session#timeout', via: :get
   get    '/login',   to: 'session#new'
   post   '/login',   to: 'session#create'
	root :to => "welcome#home", :via => [:get, :post]
   get 'welcome/home', to: 'welcome#home_view'
   get 'session/home', to: 'session#home_view_session'
	get 'records/records'
	get 'actions/actions'
	get 'employees/employees'
   get 'news/news'
   get 'reports/reports'
   get 'tasks/tasks'
   get 'hr/list'
   get 'hr/new'
   post 'hr/create'
   get 'hr/show'
   resources :linkedin
  get '/linkedin_profile', to: 'linkedin#linkedin_profile'
  get '/oauth_account', to: 'linkedin#oauth_account'
  get '/linkedin_oauth_url', to: 'linkedin#generate_linkedin_oauth_url'
  get '/index', to: 'linkedin#index'
  resources :employees
  resources :skills
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/basic_profile.rb
class BasicProfile < ApplicationRecord
	belongs_to :employee
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :subject
end

app/models/department.rb
class Department < ApplicationRecord

	has_many :employees
end

app/models/emp.rb
class Emp < ApplicationRecord
	attr_accessible :name

	validates :name, :presence => true
	has_many :empskillqualities
	has_many :skillqualities, :through => :empskillqualities
end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :department
	has_many :empskill
	has_many :skill, :through => :empskill
	has_one :basic_profile
	has_one :full_profile
	has_one :linkedin_oauth_setting
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    mount_uploader :image, ImageUploader
    self.per_page = 10

end

app/models/employeeskill.rb
class Employeeskill < ApplicationRecord

	# validates :name, presence: true

	belongs_to :employee
	belongs_to :skill
end

app/models/empskill.rb
class Empskill < ApplicationRecord
	belongs_to :employee
  	belongs_to :skill
  	has_one :linkedin_oauth_setting
end

app/models/full_profile.rb
class FullProfile < ApplicationRecord
	belongs_to :employee
end

app/models/hr.rb
class Hr < ApplicationRecord
end

app/models/manager.rb
class Manager < ApplicationRecord

	validates :password, :presence =>true, :confirmation =>true
	validates_presence_of :email, :message => "can't be empty"
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/models/skill.rb
class Skill < ApplicationRecord
	validates :name, presence: true
	has_one :linkedin_oauth_setting
	has_many :empskill
	has_many :employee, :through => :empskill
end

app/models/skillquality.rb
class Skillquality < ApplicationRecord

	attr_accessible :name

	validates :name, :presence => true
	has_many :empskillqualities
	has_many :emps, :through => :empskillqualities
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :books
end

app/models/user.rb
class User < ApplicationRecord

	validates :password, :presence =>true, :confirmation =>true
	validates_presence_of :email, :message => "can't be empty"
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  require 'will_paginate/array' 
   before_action :set_employee, only: [:show, :edit]

  

   def list
    @employees = Employee.paginate(:page =>params[:page], :per_page => 10).order('created_at DESC')
  end

	# def list
 #      @employees = Employee.order('name').page(params[:page]).per_page(10)
	# end

   def show
      @employee_skill = @employee.empskill
   end
  
   def new
      byebug
      @employee = Employee.new
      get_employees
   end

   def edit
    @employee = Employee.find(params[:id])
    @all_skills = Skill.all
   end

   # def employee_params
   #    params.require(:employees).permit(:name)
   # end

   def create
      byebug
      @employee = Employee.new(employee_params)

      params[:skills][:skill_id].each do |skill|
      byebug
         if !skill.empty?
            @employee.empskill.build(:skill_id => skill)
         end
      end

      respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, :format => @user }
        format.json { render :show, status: :created, location: @employee, :format => @user }
      else
        flash[:notice] = "Mandatory fields are empty"
        format.html { render :employees }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
   end

   

    def update
      byebug
      @employee = Employee.find(params[:id])
      
      if @employee.update_attributes(employee_param)
        params[:employee][:skill_ids].each do |skill|
        byebug
         if !skill.empty?
            @employee.empskill.build(:skill_id => skill)
            @employee.empskill.update_all(:skill_id => skill)
         end
      end
         @employee.save
         EmployeemailerMailer.employee_email(@employee).deliver
         redirect_to :action => 'show', :id => @employee
      else
         @skills = Skill.all
         render :action => 'edit'
      end
   end
   
   def delete
      Employee.find(params[:id]).destroy
      redirect_to :action => 'list'
   end


    private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_param
      params.require(:employee).permit(:name, :id, :skill,:email,:department_id,:description, :image)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employees).permit(:name, :id, :skill,:email,:department_id,:description, :image)
    end

    # utility method

    def get_employees
      @all_skills = Skill.all
      @employee_skill = @employee.empskill
       
    end

end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/emp_helper.rb
module EmpHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/hr_helper.rb
module HrHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/employees/_employee.html.erb
<%# @employees = Employee.all.paginate(:page =>params[:page], :per_page => 10) %>
 
  <tr>
      <td style= "border: 1px solid white"><%= link_to employee.name, {:action => 'show', :id => employee.id} -%></td>
      <td style= "border: 1px solid white"></td>
      <td style= "border: 1px solid white"><%= link_to employee.department.name , {:action => 'show', :id => employee.id}  %></td>
      <td style= "border: 1px solid white"></td>
      <td style= "border: 1px solid white" >
      <% employee.skill.uniq.each do |s| %>
         <br/><%= s.name %>
      <% end %> 

      </td>
      <td style= "border: 1px solid white"><%= image_tag employee.image_url.to_s  ,{:style => "width:90px; height:70px;float:right"} %></td>
      <td style= "border: 1px solid white"> <%= link_to 'Edit',edit_employee_url(:id => employee.id, :format => @user) , {:action => "edit",
      :id => employee.id} %></td>
   
      <td style= "border: 1px solid white"><%= link_to 'Linkedin', linkedin_index_url(:id => employee.id, :format => @user) %><td>
   
   </tr>

app/views/employees/_form.html.erb
<%= form_for @employee , html: {multipart: true} do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <% byebug %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div>
    <p><label for = "employee_department_id">Department:</label>
<%= collection_select(:employees, :department_id, Department.all, :id, :name, {:multiple => true}, prompt: true) %></p>
</div>

  <%= fields_for(Empskill.all) do |ab| %>
    <div class="field">
      <%= ab.label "Skills" %><br/>
      <%= collection_select(:skills, :skill_id, Skill.all, :id, :name,{}, {:multiple => true}) %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<%= render 'welcome/home' %>
<h1> Edit Employee Information Here </h1>

<%= form_for @employee, :url =>{:action => "update", :id =>@employee} do |f| %>

<p><label for = "employee_name">Name:</label>
<%= f.text_field 'name' %></p>

<p><label for = "employee_email">Email:</label>
<%= f.text_field 'email' %></p>

<p><label for = "employee_department_id">Department:</label>
<%= f.collection_select( :department_id, Department.all, :id, :name, {:multiple => true}, prompt: true) %></p>

<%= fields_for(Empskill.all) do |ab| %>
<p>
	<%= ab.label "Skills:" %>
<%= f.collection_select( :skill_ids, Skill.all, :id, :name,{}, {:multiple => true}) %></p>
<% end %>


<p><label for = "employee_description">Description:</label>
<%= f.text_area 'description' %></p>
<%= f.submit "Save changes" %>
<% end %>
<% if ! @user.blank?  %>
<%= link_to 'Back', {:action => 'list', :format => @user } %>
<% end %>

app/views/employees/employees.html.erb
<%= render 'welcome/home' %>
<h1>Create a New Employee</h1>
<% byebug %>
<%= form_tag({:action => :create}, :multipart => true) do %>
<p><label for = "employee_name">Name:</label>
<%= text_field 'employees', 'name' %></p>

<p><label for = "employee_email">Email:</label>
<%= text_field 'employees', 'email' %></p>

<p><label for = "employee_image">Employee Image:</label>
<%= file_field 'employees', 'image' %></p>

<p><label for = "employee_department_id">Department:</label>
<%= collection_select(:employees, :department_id, Department.all, :id, :name, {:multiple => true}, prompt: true) %></p>

<%= fields_for(Empskill.all) do |ab| %>
<p>
	<%= ab.label "Skills:" %>
<%= collection_select(:skills, :skill_id, Skill.all, :id, :name,{}, {:multiple => true}) %></p>
<% end %>


<p><label for = "employee_description">Description:</label>
<%= text_area 'employees', 'description' %></p>

<%= submit_tag "Create" %>

<% end -%>
<%= link_to 'Back', {:action => 'list', :format => @user} %>

        <p style="color: red;"><%= flash[:notice] %></p>

app/views/employees/list.html.erb
<%= render 'welcome/home' %>
<% byebug %>

<% if @employees.blank? %>
<p>There are not any employees currently in the system.</p>
<% else %>
<p>These are the current employees in our system</p>
<table id = "books" style= "border: 1px solid white">
<tr style= "border: 1px solid white">
<th style= "border: 1px solid white">Username</th>
<th style= "border: 1px solid white"></th>
<th style= "border: 1px solid white">Department</th>
<th style= "border: 1px solid white"></th>
<th style= "border: 1px solid white">Current Skills Of This Employees</th>
<th style= "border: 1px solid white">Employee Image</th>
</tr>
<% cache do %>
<div id="employees">
 <%= render @employees %>

</div>

<% end %>

</table>

<% end %>
<p><%= link_to "Create a New Employee", {:action => 'employees', :controller => 'employees' , :format => @user}%></p>


 
  <%= will_paginate @employees, :renderer => WillPaginate::ActionView::LinkRenderer%>

app/views/employees/list.js.erb
// $('#employees').append('<%= j render @employees %>');
<%# if @employees.next_page %>
  // $('.pagination').replaceWith('<%= j will_paginate @employees %>');
<%# else %>
  // $(window).off('scroll');
  // $('.pagination').remove();
<%# end %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<%= render 'welcome/home' %>
<h1>Employee Details</h1>
<% cache @employee do %>
<p>
   <strong>Name: </strong> <%= @employee.name %><br />
   <strong>image: </strong> <%= image_tag @employee.image_url.to_s  ,{:style => "width:30px;"} %><br />
   <strong>Department :</strong> <%= @employee.department.name %><br />
   <strong>Created Date:</strong> <%= @employee.created_at %><br />
</p>

<p><%= @employee.description %></p>
<% end %>
<hr />
<% if ! session[:user_id].blank?  %>
<%= link_to 'Back', {:action => 'list'} %>
<% end %>

app/views/employees/single_empdetail.html.erb
<%= render 'welcome/home' %>
<% employee = Employee.find_by(email: params[:session][:email]) %>
<% byebug %>
<table id = "books" style= "border: 1px solid white">
<tr style= "border: 1px solid white">
<th style= "border: 1px solid white">Username</th>
<th style= "border: 1px solid white"></th>
<th style= "border: 1px solid white">Department</th>
<th style= "border: 1px solid white"></th>
<th style= "border: 1px solid white">Current Skills Of This Employees</th>
<th style= "border: 1px solid white">Employee Image</th>
</tr>
<tr>
      <td style= "border: 1px solid white"><%= employee.name -%></td>
      <td style= "border: 1px solid white"></td>
      <td style= "border: 1px solid white"><%= employee.department.name  %></td>
      <td style= "border: 1px solid white"></td>
      <td style= "border: 1px solid white" >
      <% employee.skill.uniq.each do |s| %>
         <br/><%= s.name %>
      <% end %> 

      </td>
      <td style= "border: 1px solid white"><%= image_tag employee.image_url.to_s  ,{:style => "width:90px; height:70px;float:right"} %></td>
      <td style= "border: 1px solid white"> <%= link_to 'Edit',edit_employee_url(:id => employee.id, :format => @user) , {:action => "edit",
      :id => employee.id} %></td>
   
      <td style= "border: 1px solid white"><%= link_to 'Linkedin', linkedin_index_url(:id => employee.id, :format => @user) %><td>
   
   </tr>


</table>