config/routes.rb
Rails.application.routes.draw do
   get 'book/list'
   devise_for :users, controllers: { sessions: "session/new" }
   get 'book/new'
   root 'session#new'
   post 'book/create'
   post 'employees/create'
   get 'employees/list'
   get 'employees/show'
   get 'employees/new'
   get 'employees/edit'
   get 'employees/update'
   post 'manager/create'
   get 'manager/list'
   get 'manager/show'
   get 'manager/new'
   patch 'book/update'
   get 'book/list'
   get 'book/show'
   get 'book/edit'
   get 'book/delete'
   get 'book/update'
   get 'book/show_subjects'
   get 'user/list'
   get 'user/new'
   post 'user/create'
   get 'user/show'
   get 'application/session_time'
   match 'active'  => 'session#active',  via: :get
   match 'timeout' => 'session#timeout', via: :get
   get    '/login',   to: 'session#new'
   post   '/login',   to: 'session#create'
	root :to => "welcome#home", :via => [:get, :post]
   get 'welcome/home', to: 'welcome#home_view'
   get 'session/home', to: 'session#home_view_session'
	get 'records/records'
	get 'actions/actions'
	get 'employees/employees'
   get 'news/news'
   get 'reports/reports'
   get 'tasks/tasks'
   get 'hr/list'
   get 'hr/new'
   post 'hr/create'
   get 'hr/show'
   resources :linkedin
  get '/linkedin_profile', to: 'linkedin#linkedin_profile'
  get '/oauth_account', to: 'linkedin#oauth_account'
  get '/linkedin_oauth_url', to: 'linkedin#generate_linkedin_oauth_url'
  get '/index', to: 'linkedin#index'
  resources :employees
  resources :skills
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/basic_profile.rb
class BasicProfile < ApplicationRecord
	belongs_to :employee
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :subject
end

app/models/department.rb
class Department < ApplicationRecord

	has_many :employees
end

app/models/emp.rb
class Emp < ApplicationRecord
	attr_accessible :name

	validates :name, :presence => true
	has_many :empskillqualities
	has_many :skillqualities, :through => :empskillqualities
end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :department
	has_many :empskill
	has_many :skill, :through => :empskill
	has_one :basic_profile
	has_one :full_profile
	has_one :linkedin_oauth_setting
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    mount_uploader :image, ImageUploader
    self.per_page = 10

end

app/models/employeeskill.rb
class Employeeskill < ApplicationRecord

	# validates :name, presence: true

	belongs_to :employee
	belongs_to :skill
end

app/models/empskill.rb
class Empskill < ApplicationRecord
	belongs_to :employee
  	belongs_to :skill
  	has_one :linkedin_oauth_setting
end

app/models/full_profile.rb
class FullProfile < ApplicationRecord
	belongs_to :employee
end

app/models/hr.rb
class Hr < ApplicationRecord
end

app/models/manager.rb
class Manager < ApplicationRecord

	validates :password, :presence =>true, :confirmation =>true
	validates_presence_of :email, :message => "can't be empty"
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
end

app/models/skill.rb
class Skill < ApplicationRecord
	validates :name, presence: true
	has_one :linkedin_oauth_setting
	has_many :empskill
	has_many :employee, :through => :empskill
end

app/models/skillquality.rb
class Skillquality < ApplicationRecord

	attr_accessible :name

	validates :name, :presence => true
	has_many :empskillqualities
	has_many :emps, :through => :empskillqualities
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :books
end

app/models/user.rb
class User < ApplicationRecord

	validates :password, :presence =>true, :confirmation =>true
	validates_presence_of :email, :message => "can't be empty"
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	

end

app/controllers/session_controller.rb
require 'byebug'
class SessionController < ApplicationController

	def new
	
	end

  def create
    user = User.find_by(email: params[:session][:email])
    employee = Employee.find_by(email: params[:session][:email])
    if ! user.blank?
    	session[:user_id] = user.id
    end
    # session[:user_id] = user.id
    manager = Manager.find_by(email: params[:session][:email])
	if ! user.nil? 
		begin
			if user.password == params[:session][:password]
				render 'welcome/home' 	
			else
				# Create an error message.
				render 'user/new'
			end
		rescue
			flash[:notice] = "password doesn't match or fields are empty".html_safe
			render :action => :new, :controller => session
		end
	elsif ! manager.nil?
		if manager.password == params[:session][:password]
			render 'welcome/home'
		else
			render 'user/new'
		end
	elsif ! employee.nil?
		if employee.email == params[:session][:email]
			render 'employees/single_empdetail'	
		else 
			render 'user/new'
		end
	else
		flash[:notice] = "Email and password are empty"
		render :action => :new, :controller => session
	end
    
   
  end

  def active
    render_session_status
  end


  def timeout
  	flash[:notice] = "Your session has been timed out"
  	rediect_to "/user/new"
  end

  

  def home_view_session
  	render 'session/home'

  end
  
  def show
  
  end

  def destroy
  end
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/emp_helper.rb
module EmpHelper
end

app/helpers/hr_helper.rb
module HrHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
	
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/session/home.html.erb
<div class="menu2">
    <%= image_tag('logo.png') %>
	<% @user = User.find_by(id: params[:format]) %>
    <% session[:user] = @user %>
	<% byebug %>
	<a><%= link_to "Home" , session_home_url(@user)  %></a>
	<a><%#= link_to "Profile" , session_home_url(@user) %> </a>
    <a><%= link_to "News",  news_news_url(@user) %></a>
    <a class="current"><%= link_to "Tasks", tasks_tasks_url(@user) %></a>
    <a><%= link_to "Records",  records_records_url(@user) %></a>
    <a href="#4"><%= link_to "Reports", reports_reports_url(@user) %></a>
    <a href="#5"><%= link_to "Actions",  actions_actions_url(@user) %></a>
    <a class="dummy"> </a>
	<a><%= link_to "Logout", {:action => 'new', :controller => 'session' } ,{:style => "padding-left:95%"}%></a>
</div>
<br/>
<% if ! session[:user_id].blank?  %>
<a style="color:white;"><%= link_to 'Click here to sign up as Admin User', {:action => 'new', :controller => 'user', :format =>@user} ,{:style => "color: white;"} %></a>
<br/>
<br/>
<a><%= link_to 'Click here to sign up as Manager', {:action => 'new', :controller => 'manager', :format => @user} ,{:style => "color: white;"}%></a>
<br/>
<br/>
<a><%= link_to 'Click here to sign up as HR', {:action => 'new', :controller => 'hr', :format => @user} ,{:style => "color: white;"}%></a>
<br/>
<br/>
<a><%= link_to 'Click here to create a New Skill', {:action => 'new', :controller => 'skills', :format => @user} ,{:style => "color: white;"}%></a>
<% else %>
<a>Manager or Employee</a>
<% end %>

app/views/session/new.html.erb
<%= image_tag('logo.png') %>
<h1 style="text-align:center;">HR Application</h1>

	<body>
  <div class="form">
      
      <ul class="tab-group">
        <!-- <li class="tab active"><%= link_to 'New User Sign Up', {:action => 'new', :controller => 'user'} %></li> -->
      </ul>
        
        <div id="login">  
		
          <h2 style="background-color: #0087be;text-align:center;">Login In Here</h2>
	
	<%= form_for(:session, url: login_path) do |f| %>

      <%=  f.label :email, 'Enter Email Here' , {:style=> "background-color: #0087be;"}%>
      <%= f.email_field :email, class: 'form-control' %>
		
      <%=  f.label :password, 'Enter Password Here' , {:style=> "background-color: #0087be;"}%>
      <%= f.password_field :password, class: 'form-control' %>
		
     <button class="button button-block" style="background-color: white;"/> <%= f.submit "Log in", {:style=> "color:white; background-color:#0087be;font-size:15px;font-family:martel;cursor:pointer;", :class=> "btn btn-primary"} %></button>
	 <% end %>
	 
	 <%#= flash[:notice]%>
        </div>
        <p style="color: red;"><%= flash[:notice] %></p>
      </div><!-- tab-content -->
      
</div> <!-- /form -->

</body>
	
	

app/views/session/show.html.erb
<%# if flash[:notice] %>
    <div class="notice"><%#= flash[:notice] %></div>
  <%# end %>